CI: enable qa_agc test now that it has been fixed (#5244).
Keep qa_agc disabled on Windows because it can still fail for another
reason, e.g.:

FAIL: test_006 (__main__.test_agc)
Test the complex AGC loop (attack and decay rate inputs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Miniconda3/conda-bld/gnuradio-dev_1636670849640/work/gr-analog/python/analog/qa_agc.py", line 476, in test_006
    self.assertFloatTuplesAlmostEqual(result, M * [ref, ], 4)
  File "C:/Miniconda3/conda-bld/gnuradio-dev_1636670849640/work/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 100, in assertFloatTuplesAlmostEqual
    return all([
  File "C:/Miniconda3/conda-bld/gnuradio-dev_1636670849640/work/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 101, in <listcomp>
    self.assertAlmostEqual(x, y, places, msg)
AssertionError: 1.084648370766092 != 1 within 4 places (0.08464837076609211 difference)

Signed-off-by: Ryan Volz <ryan.volz@gmail.com>